language: python
python:
  - "3.4"

install:

  # - "pip install http://www.nltk.org/nltk3-alpha/nltk-3.0a4.tar.gz"
  - "pip install nltk"
  - "pip install -r requirements.txt"

# command to run tests, e.g. python setup.py test
script:
  - cd cltk/tests/
  - python test_cltk.py
